language: java
jdk: oraclejdk13

cache:
  directories:
    - $HOME/.m2 

before install: mkdir -p ~/.m2 && cp settings.xml ~/.m2/settings.xml
install: mvn clean install -DskipTests=true
script: mvn test -Dassembly.skipAssembly=true