language: java
jdk: oraclejdk13

cache:
  directories:
    - $HOME/.m2 

before install: powershell mkdir -force ~/.m2 ; cp settings.xml ~/.m2/settings.xml
install: mvn clean install -DskipTests=true -U
script: mvn test -Dassembly.skipAssembly=true